### ISSUE TITLE
"Maximum number of clients reached" when running DisplayInfo::all() multiple times

### ISSUE THREAD

**Issue by mdacach** [nashaofu/display-info#1]
Hello, hope this message finds you well! First of all, thank you for your work. The `screenshots` crate is great.

I am running into an issue on [screenshots crate](https://crates.io/crates/screenshots) which I've tracked up to here. There's a link to a video showing the issue at the bottom.
#### The Issue
When calling `DisplayInfo::all()` multiple times, the error "Maximum number of clients reached" shows up.

#### Possible Explanation
Each call to `DisplayInfo::all()` is creating a connection to X that is not being closed. This leads to too many connections, and X refuses a new one.

#### Example
This is a [simple script](https://github.com/mdacach/display_info_test/tree/main) which calls `DisplayInfo::all()` in a loop:
![image](https://user-images.githubusercontent.com/43617028/177450384-f0589cfd-24e9-4167-bcf0-9a047e8ee735.png)

Eventually, this happens. Calls up to 178 were fine, but starting there, we have "Maximum number of clients reached".
![image](https://user-images.githubusercontent.com/43617028/177450454-919c0c9d-4307-4b85-9bb4-fc8023ca98fc.png)

This is a [3-minute video](https://www.dropbox.com/s/qseowr2pnetre4y/display_info_issue.mp4?dl=0) walking through the issue.

Unfortunately, I could not get it working. I tried adding some `XCloseDisplay` calls throughout the code, but it didn't work (segfaults and whatnot). I hope the video helps, and thank you once again for your work.

####  Resources
Script's source code:
https://github.com/mdacach/display_info_test/tree/main
Video explaining the issue:
https://www.dropbox.com/s/qseowr2pnetre4y/display_info_issue.mp4?dl=0
Function where I think the problem is:
https://github.com/nashaofu/display-info/blob/067a7adebefba72be81331975c04868b47d6b2f2/src/linux.rs#L11

**Comment by mdacach** [comment]
Works perfectly! Thank you very much.
May I ask, out of curiosity:
1 - What was exactly the problem? I could not solve it by just adding a XCloseDisplay call (the code double-freed, I think).
2 - Where do I find documentation regarding XRR functions such as `XRRFreeScreenResources`? I did not find anything on the web.

**Comment by nashaofu** [comment]
> Works perfectly! Thank you very much. May I ask, out of curiosity: 1 - What was exactly the problem? I could not solve it by just adding a XCloseDisplay call (the code double-freed, I think). 2 - Where do I find documentation regarding XRR functions such as `XRRFreeScreenResources`? I did not find anything on the web.

1. The problem caused by [this commit](https://github.com/nashaofu/display-info/commit/d66c6991d8e9a897abd9184f1d80f00e07f8ecda), I found it would be released twice，So remove XCloseDisplay，the possible reason is that the following code releases XDisplay first. https://github.com/nashaofu/display-info/blob/d66c6991d8e9a897abd9184f1d80f00e07f8ecda/src/linux.rs#L27-L37
2. Official documentation: https://www.x.org/releases/X11R7.5/doc/index.html.

**Comment by mdacach** [comment]
Thank you!
