### ISSUE TITLE
Getting wrong scale_factor

### ISSUE THREAD

**Issue by sandyfigueroa** [nashaofu/display-info#25]
SO: Windows 11
display-info version: "0.4.3"

I am using this library to get information about my monitors.

Right now I have two screens, one is the one integrated in my laptop (1920x1080, scale factor 1.25) and an external one (2560x1080, scale factor 1)

Using `DisplayInfo::all()` to get the information and printing the scale_factor for all the monitors gives me a scale factor of `1` for all of them.

The other information seems to be ok, for example, the resolution (same ones I mentioned before) but the scale factor is wrong.

No matter if I have the external monitor connected or disconnected, I always get a scale factor of `1` for my integrated screen, which it is actually 1.25 (125%).

I need to do some calculations with this number, but they are wrong, since I cannot get the correct value for it using this library.

Tried using this library on Electronjs using Node-API, and also on Tauri, but the same issue on both.

I am just printing it like this:

```rust
                println!("Scale factor: {}", display_info.scale_factor);
                println!("x: {}, y: {}", display_info.x, display_info.y);
                println!(
                    "Width: {}, Height: {} \n",
                    display_info.width, display_info.height
                );
```
This is what I get:

```
Scale factor: 1
x: 0, y: 0
Width: 1920, Height: 1080

Scale factor: 1
x: 1920, y: 0
Width: 2560, Height: 1080
```
![image](https://github.com/nashaofu/display-info/assets/13713107/1e89f201-23a0-41dc-ae0b-0e7197909f4c)

But my monitor:
![image](https://github.com/nashaofu/display-info/assets/13713107/ac29e204-b573-46ef-b9f8-7767f35a1721)

**Comment by nashaofu** [comment]
This library is consistent with the return value of electron, but in the next version I will add a property to provide the actual zoom ratio,

**Comment by nashaofu** [comment]
I can't reproduce this issue on my computer, but I tried modifying the code. Could you test the code on your computer?https://github.com/nashaofu/display-info/pull/26

**Comment by luftaquila** [comment]
Hello, same issue happens here, at Windows 11 Home 23H2 and display-info v0.5.1.

The `scale_factor` is always set to `1`, while the `width` and `height` is set to its logical pixels.

![image](https://github.com/nashaofu/display-info/assets/17094868/5c6d3e48-a644-443d-a728-721523641ddf)

```
DisplayInfo { name: "\\\\.\\DISPLAY11", id: 1989980034, raw_handle: HMONITOR(65537), x: 0, y: 0, width: 1440, height: 960, rotation: 0.0, scale_factor: 1.0, frequency: 60.0, is_primary: true }
```

When I set the scale to 100% at Windows Settings, only width and height changes(as expected). Setting it again as 200% does not affects the `DisplayInfo.scale_factor`.

```
 DisplayInfo { name: "\\\\.\\DISPLAY11", id: 1989980034, raw_handle: HMONITOR(65537), x: 0, y: 0, width: 2880, height: 1920, rotation: 0.0, scale_factor: 1.0, frequency: 60.0, is_primary: true }
```

Thank you for writing a great crate! Hope it would fixed someday.

**Comment by nashaofu** [comment]
@luftaquila Is it the latest version?

**Comment by luftaquila** [comment]
Yup. `display-info` is v0.5.1 as I mentioned before.
