### ISSUE TITLE
display-info 0.4.9 breaks semver compatibility, please yank it

### ISSUE THREAD

**Issue by kellda** [nashaofu/display-info#35]
Since 0.4.9, the `DisplayInfo` struct no longer derives `Copy`, which is a breaking change. You may already be aware of this, as version 0.5.0 was recently released. Releasing a version with the correct number is good but not sufficient to prevent breakages. The erroneous version 0.4.9 must also be yanked.
Thank you in advance!

**Comment by nashaofu** [comment]
done
